name: Telegram RSS (Node)

on:
  push:
    branches: [ main ]   # push-ra is tesztel
  schedule:
    - cron: "*/3 * * * *"   # 3 percenként
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Ha van lockfile, ci-t használunk, különben install
      - name: Install deps (ci)
        if: ${{ hashFiles('package-lock.json') != '' }}
        run: npm ci --omit=dev --no-audit --no-fund

      - name: Install deps (no lockfile)
        if: ${{ hashFiles('package-lock.json') == '' }}
        run: npm install --omit=dev --no-audit --no-fund

      - name: Run RSS script
        - name: Run RSS script
  env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
    GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
    GIST_ID: ${{ secrets.GIST_ID }}   # első futásnál lehet üres
    MAX_ITEMS_PER_FEED: "10"
    SEND_DELAY_MS: "500"
    DEBUG: "0"                        # ideiglenesen állíthatod "1"-re

    # --- Google News beállítások ---
    GNEWS_FROM_KEYWORDS: "1"          # kulcsszavakból automatikus GNews feedek
    GNEWS_HL: "hu"
    GNEWS_GL: "HU"
    GNEWS_CEID: "HU:hu"
    GNEWS_WHEN: "3d"                  # opcionális: csak az elmúlt 3 nap
    GNEWS_EXTRA: "-recipe -cooking"   # opcionális: extra kizárások/szűkítés
  run: npm run rss:run

